version: '3'

services:
  postgres:
    image: postgres:10
    restart: on-failure
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
    - /mnt/alendo-api.auction.chvcm.ru-postgres:/var/lib/postgresql/data
  redis:
    image: redis:4
    restart: on-failure
    ports:
    - 6379:6379
    volumes:
    - /mnt/alendo-api.auction.chvcm.ru-redis:/data
