version: '3'

services:
  web:
    build:
      context: ../
      dockerfile: docker/web/Dockerfile
      args:
        RECAPTCHA_SITE: "${RECAPTCHA_SITE}"
    restart: "${COMPOSE_RESTART}"
    ports:
      - "${WEB_PORT}:80"
    env_file:
      - web/.env
    depends_on:
      - postgres
      - redis
      - s3proxy
      - mail
  mail:
    image: "analogic/poste.io:${MAIL_TAG}"
    hostname: "${MAIL_HOSTNAME}"
    dns: mail-dnsmasq
    restart: "${COMPOSE_RESTART}"
    ports:
      - "${MAIL_PORT_WEB}:80"
    environment:
      HTTPS: 'OFF'
      DISABLE_CLAMAV: 'TRUE'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "${MAIL_VOLUME}:/data"
    depends_on:
      - mail-dnsmasq
  mail-dnsmasq:
    image: "andyshinn/dnsmasq:${MAIL_DNSMASQ_TAG}"
    command: ["--address=/#/127.0.0.1"]
    cap_add:
      - NET_ADMIN
    restart: "${COMPOSE_RESTART}"
