version: '3'

services:
  postgres:
    image: "postgres:${POSTGRES_TAG}"
    restart: "${COMPOSE_RESTART}"
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - "${POSTGRES_VOLUME}:/var/lib/postgresql/data"
  redis:
    image: "redis:${REDIS_TAG}"
    restart: "${COMPOSE_RESTART}"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - "${REDIS_VOLUME}:/data"
  s3proxy:
    image: "andrewgaul/s3proxy:${S3PROXY_TAG}"
    restart: "${COMPOSE_RESTART}"
    ports:
      - "${S3PROXY_PORT}:80"
    environment:
      S3PROXY_IDENTITY: "${S3PROXY_ACCESS_KEY_ID}"
      S3PROXY_CREDENTIAL: "${S3PROXY_SECRET_ACCESS_KEY}"
    volumes:
      - "${S3PROXY_VOLUME}:/data"
