/**
 * API codes
 */
export enum ApiCodes {
  // default
  BAD_REQUEST = "BAD_REQUEST",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE",
  UNKNOWN_CODE = "UNKNOWN_CODE",
  // custom
  ATTACHMENT_NOT_FOUND_BY_NAME = "ATTACHMENT_NOT_FOUND_BY_NAME",
  BANNED = "BANNED",
  EMPLOYEE_NOT_FOUND_BY_ID = "EMPLOYEE_NOT_FOUND_BY_ID",
  ENTITY_FOUND_BY_ITN = "ENTITY_FOUND_BY_ITN",
  ENTITY_FOUND_BY_ITN_AND_PSRN = "ENTITY_FOUND_BY_ITN_AND_PSRN",
  ENTITY_FOUND_BY_PSRN = "ENTITY_FOUND_BY_PSRN",
  ENTITY_NOT_FOUND_BY_ID = "ENTITY_NOT_FOUND_BY_ID",
  JWT_VERIFY_USER = "JWT_VERIFY_USER",
  LOT_NOT_FOUND_BY_ID = "LOT_NOT_FOUND_BY_ID",
  RECAPTCHA_V2 = "RECAPTCHA_V2",
  RECOVERY_CODE_NOT_FOUND = "RECOVERY_CODE_NOT_FOUND",
  REQUIRED_ADMIN = "REQUIRED_ADMIN",
  REQUIRED_MODERATOR = "REQUIRED_MODERATOR",
  REQUIRED_SAME_ENTITY_OR_MODERATOR = "REQUIRED_SAME_ENTITY_OR_MODERATOR",
  REQUIRED_VERIFIED_ENTITY = "REQUIRED_VERIFIED_ENTITY",
  STUFF_NOT_FOUND_BY_ID = "STUFF_NOT_FOUND_BY_ID",
  STUFF_TRANSLATION_NOT_FOUND_BY_CODE = "STUFF_TRANSLATION_NOT_FOUND_BY_CODE",
  USER_FOUND_BY_EMAIL = "USER_FOUND_BY_EMAIL",
  USER_FOUND_BY_EMAIL_AND_PHONE = "USER_FOUND_BY_EMAIL_AND_PHONE",
  USER_FOUND_BY_PHONE = "USER_FOUND_BY_PHONE",
  USER_NOT_FOUND_BY_EMAIL = "USER_NOT_FOUND_BY_EMAIL",
  USER_NOT_FOUND_BY_EMAIL_AND_PASSWORD = "USER_NOT_FOUND_BY_EMAIL_AND_PASSWORD",
  USER_NOT_FOUND_BY_PASSWORD_RESET_TOKEN = "USER_NOT_FOUND_BY_PASSWORD_RESET_TOKEN",
  USER_NOT_FOUND_BY_PURGATORY_TOKEN = "USER_NOT_FOUND_BY_PURGATORY_TOKEN",
  WRONG_OTP_TOKEN = "WRONG_OTP_TOKEN",
}
